SecureShare/Controllers/PriceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SecureShare.Website.Controllers
{
    public class PriceController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
       
    }
}

SecureShare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SecureShare</title>

    <environment include="Development">
        <link href="~/lib/bootstrap-4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
    </environment>
</head>
<body>
@await Html.PartialAsync("_NavbarPartial")
@RenderBody()

    <environment include="Development">
        <script src="~/lib/jQuery-3.2.1/jquery-3.2.1.slim.min.js"></script>
       <script src="~/lib/popper.js-1.14.1/popper.min.js"></script>
        <script src="~/lib/bootstrap-4.0.0/js/bootstrap.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous"></script>
       <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.1/popper.min.js"
             integrity="sha256-ST2MecrXrJaAsqmfpk9XRQITlDoyMmUtgKBEndDisSc="
             crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"></script>
    </environment>
@RenderSection("Scripts", required: false)
</body>
</html>

SecureShare/Views/Shared/_NavbarPartial.cshtml
<link rel="stylesheet" href="~/css/navbar.css"/>

<nav class="navbar navbar-dark navbar-custom navbar-expand-lg sticky-top fixed-top" style="overflow:hidden;">
    <a class="navbar-brand" href="">SecureShare</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" ></span>
    </button>

    <div class="collapse navbar-collapse " id="navbar">
        <ul class="navbar-nav mr-auto" >
            <li class="nav-item ">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" asp-area="" asp-controller="Price" asp-action="Index">Prices</a>
            </li>

            @if (User.Identity.IsAuthenticated)
    {
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="PrivateUser" asp-action="Dashboard">Dashboard</a>
        </li>
}
        </ul>

        @await Html.PartialAsync("_LoginPartial")
    </div>
</nav>